version: "3"

services:
  # Quarkus API
#  quarkus-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: quarkus-app
#    environment:
#      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/postgres
#      - QUARKUS_DATASOURCE_USERNAME=postgres
#      - QUARKUS_DATASOURCE_PASSWORD=postgres
#      - EMBEDDING_SERVICE_URL=http://embedding-server:5005
#    depends_on:
#      - db
#      - embedding-server
#    ports:
#      - "8080:8080"

  # Postgres Vector
  db:
    image: ankane/pgvector
    container_name: postgres-ai
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  # Embedding Server
  embedding-server:
    build:
      context: ./embedding_server
      dockerfile: Dockerfile
    container_name: embedding-server
    ports:
      - "5005:5005"
    restart: always