version: "3"

services:
  db:
    image: ankane/pgvector
    container_name: postgres-ai
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  embedding-server:
    build:
      context: ./embedding_server
      dockerfile: Dockerfile
    container_name: embedding-server
    ports:
      - "5005:5005"
    restart: always